[package]
name = "phone"
version = "0.1.0"
authors = ["slixperi <rmccarth@andrew.cmu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.12"
regex = "0.1.41"
argparse = "0.2.2"
